
int isNegOne(int);
int test_isNegOne(int);
int logicalAnd(int);
int test_logicalAnd(int);
int bitZor(int, int);
int test_bitZor(int, int);
int isLessNegTwo(int);
int test_isLessNegTwo(int);
int decOK();
int test_decOK();
int incOK();
int test_incOK();
int isBetween(int, int);
int test_isBetween(int, int);
int bitSwap(int, int, int);
int test_bitSwap(int, int, int);
int logicalOr(int);
int test_logicalOr(int);
int rotate(int, int);
int test_rotate(int, int);
int negVal(int);
int test_negVal(int);
int twocomp2onecomp(int);
int test_twocomp2onecomp(int);
unsigned float_range(unsigned);
unsigned test_float_range(unsigned);
unsigned float_gtOne(unsigned);
unsigned test_float_gtOne(unsigned);
unsigned float_exactInt(unsigned);
unsigned test_float_exactInt(unsigned);
